import { PathProps } from "./types";

export const Path: PathProps = {
  sendOtp: "/api/send-otp",
  validateData: "/api/validate-data",
  validateOtp: "/api/validate-otp",
  register: "/api/register",
  login: "/api/login",
  trainers: "/api/trainers",
  admins: "/api/admin",
  plans: "/api/plans",
  logout: "/api/logout",
  forgotPassword: "/api/forgot-password",
  resetPassword: "/api/reset-password",
  google: "/api/auth",
  user: "/api/user",
  getRoutines: "/api/routines",
  warmUps: "/api/warm-ups",
  specialCases: "/api/special-cases",
  routineDays: "/api/routine-days",
  weight: "/api/weight",
  routineExercises: "/api/routine-exercises",
  profile: "/api/profile",
  exercises: "/api/exercises",
};
